version: '3.8'
services:
    m294-webapi:
        image: manuelbachofner/m294webapi:latest
        container_name: m294-webapi
        restart: always
        ports:
            - 2940:4000  
    m294-auth:
        image: manuelbachofner/m294auth:latest
        container_name: m294-auth
        restart: always
        ports:
            - 2941:3000  